name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"   # Every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:

      # Run Snake Animation
      - name: Generate Snake SVG
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Nimish-go
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Push Snake SVG to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: main
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
